/*
  Ajax
  - Ready State => Status Of The Request
  [0] Request Not Initialized
  [1] Server Connection Established
  [2] Request Received
  [3] Processing Request
  [4] Request Is Finished And Response Is Ready
  - Status
  [200] Response Is Successful
  [404] Not Found
*/

let myRequest = new XMLHttpRequest();
myRequest.open("GET", "https://api.github.com/users/haithamabudraz/repos");
myRequest.send();
console.log(myRequest);

myRequest.onreadystatechange = function () {
  // console.log(myRequest.readyState);
  // console.log(myRequest.status);
  if (this.readyState === 4 && this.status === 200) {
    console.log(this.responseText);
  }
};
/*
[
  {
    "id": 1201130915,
    "node_id": "R_kgDOR5fNow",
    "name": "coursera-frontend-developer-course",
    "full_name": "HaithamAbuDraz/coursera-frontend-developer-course",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/coursera-frontend-developer-course",
    "description": "A structured repository documenting my progress through the Coursera Front-End Developer Learning Path. Includes projects, exercises, and notes covering HTML, CSS, JavaScript, and modern front-end tools.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/coursera-frontend-developer-course/deployments",
    "created_at": "2026-04-04T08:52:17Z",
    "updated_at": "2026-04-04T09:03:54Z",
    "pushed_at": "2026-04-04T09:00:13Z",
    "git_url": "git://github.com/HaithamAbuDraz/coursera-frontend-developer-course.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/coursera-frontend-developer-course.git",
    "clone_url": "https://github.com/HaithamAbuDraz/coursera-frontend-developer-course.git",
    "svn_url": "https://github.com/HaithamAbuDraz/coursera-frontend-developer-course",
    "homepage": "",
    "size": 1,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "bootstrap",
      "coursera",
      "coursera-frontend",
      "css",
      "figma",
      "front-end-developer",
      "front-end-web-development",
      "html5",
      "javascript",
      "react"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 947175468,
    "node_id": "R_kgDOOHTALA",
    "name": "Data-Structures-Java",
    "full_name": "HaithamAbuDraz/Data-Structures-Java",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/Data-Structures-Java",
    "description": "A complete collection of fundamental data structures, including arrays, linked lists, stacks, queues, trees, graphs, and hash tables. Each structure comes with implementations, explanations, and examples to enhance problem-solving skills in Java. 🚀",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/Data-Structures-Java/deployments",
    "created_at": "2025-03-12T09:19:47Z",
    "updated_at": "2025-03-12T09:48:09Z",
    "pushed_at": "2025-03-12T09:36:16Z",
    "git_url": "git://github.com/HaithamAbuDraz/Data-Structures-Java.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/Data-Structures-Java.git",
    "clone_url": "https://github.com/HaithamAbuDraz/Data-Structures-Java.git",
    "svn_url": "https://github.com/HaithamAbuDraz/Data-Structures-Java",
    "homepage": null,
    "size": 62,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "Java",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main"
  },
  {
    "id": 1218029734,
    "node_id": "R_kgDOSJmopg",
    "name": "elzero-html-css-template-one",
    "full_name": "HaithamAbuDraz/elzero-html-css-template-one",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/elzero-html-css-template-one",
    "description": "This repository contains my implementation of Template One from Elzero Web School's \"HTML & CSS Template One 2021\" playlist. A beginner-friendly project covering layout, styling, and responsive design principles.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/elzero-html-css-template-one/deployments",
    "created_at": "2026-04-22T13:13:21Z",
    "updated_at": "2026-04-29T08:16:47Z",
    "pushed_at": "2026-04-29T08:16:43Z",
    "git_url": "git://github.com/HaithamAbuDraz/elzero-html-css-template-one.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/elzero-html-css-template-one.git",
    "clone_url": "https://github.com/HaithamAbuDraz/elzero-html-css-template-one.git",
    "svn_url": "https://github.com/HaithamAbuDraz/elzero-html-css-template-one",
    "homepage": "https://haithamabudraz.github.io/elzero-html-css-template-one/",
    "size": 855,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "css",
      "elzero-template",
      "elzero-web-school",
      "html",
      "html-and-css-template-1",
      "leon-template"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 863443890,
    "node_id": "R_kgDOM3cbsg",
    "name": "HaithamAbuDraz",
    "full_name": "HaithamAbuDraz/HaithamAbuDraz",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/HaithamAbuDraz",
    "description": "Config files for my GitHub profile.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/HaithamAbuDraz/deployments",
    "created_at": "2024-09-26T09:56:30Z",
    "updated_at": "2026-03-30T14:30:00Z",
    "pushed_at": "2026-03-30T14:29:53Z",
    "git_url": "git://github.com/HaithamAbuDraz/HaithamAbuDraz.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/HaithamAbuDraz.git",
    "clone_url": "https://github.com/HaithamAbuDraz/HaithamAbuDraz.git",
    "svn_url": "https://github.com/HaithamAbuDraz/HaithamAbuDraz",
    "homepage": "https://github.com/HaithamAbuDraz",
    "size": 15,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": null,
    "has_issues": false,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "config",
      "github-config"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1194336910,
    "node_id": "R_kgDORzAijg",
    "name": "javascript-elzero-bootcamp",
    "full_name": "HaithamAbuDraz/javascript-elzero-bootcamp",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/javascript-elzero-bootcamp",
    "description": "My journey through Elzero Web School JavaScript Bootcamp - Complete course lessons, challenges, assignments, projects.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/javascript-elzero-bootcamp/deployments",
    "created_at": "2026-03-28T08:02:00Z",
    "updated_at": "2026-04-29T11:38:08Z",
    "pushed_at": "2026-04-29T11:38:04Z",
    "git_url": "git://github.com/HaithamAbuDraz/javascript-elzero-bootcamp.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/javascript-elzero-bootcamp.git",
    "clone_url": "https://github.com/HaithamAbuDraz/javascript-elzero-bootcamp.git",
    "svn_url": "https://github.com/HaithamAbuDraz/javascript-elzero-bootcamp",
    "homepage": "",
    "size": 376,
    "stargazers_count": 1,
    "watchers_count": 1,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": false,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [
      "elzero-js-assignments",
      "elzero-js-bootcamp",
      "elzero-web-school",
      "javascript",
      "javascript-elzero-bootcamp",
      "js",
      "web-development"
    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 1,
    "default_branch": "main"
  },
  {
    "id": 1011059853,
    "node_id": "R_kgDOPEOMjQ",
    "name": "Modern-Login-Sign-Up-Form",
    "full_name": "HaithamAbuDraz/Modern-Login-Sign-Up-Form",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/Modern-Login-Sign-Up-Form",
    "description": "A sleek, animated, and fully responsive Login/Signup page built using HTML, CSS, and JavaScript. Designed for modern web applications that require stylish and functional user authentication interfaces.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/Modern-Login-Sign-Up-Form/deployments",
    "created_at": "2025-06-30T08:39:08Z",
    "updated_at": "2026-03-28T10:01:06Z",
    "pushed_at": "2025-06-30T09:37:53Z",
    "git_url": "git://github.com/HaithamAbuDraz/Modern-Login-Sign-Up-Form.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/Modern-Login-Sign-Up-Form.git",
    "clone_url": "https://github.com/HaithamAbuDraz/Modern-Login-Sign-Up-Form.git",
    "svn_url": "https://github.com/HaithamAbuDraz/Modern-Login-Sign-Up-Form",
    "homepage": "https://haithamabudraz.github.io/Modern-Login-Sign-Up-Form/",
    "size": 1442,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "CSS",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 946522914,
    "node_id": "R_kgDOOGrLIg",
    "name": "My-Website",
    "full_name": "HaithamAbuDraz/My-Website",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/My-Website",
    "description": "This is my personal portfolio website showcasing my work as a web developer. It includes an \"About Me\" section, a portfolio of projects, links to my freelancing profiles, and a contact form.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/My-Website",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/My-Website/deployments",
    "created_at": "2025-03-11T09:20:32Z",
    "updated_at": "2026-03-28T10:01:08Z",
    "pushed_at": "2025-03-12T09:49:56Z",
    "git_url": "git://github.com/HaithamAbuDraz/My-Website.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/My-Website.git",
    "clone_url": "https://github.com/HaithamAbuDraz/My-Website.git",
    "svn_url": "https://github.com/HaithamAbuDraz/My-Website",
    "homepage": null,
    "size": 29,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  },
  {
    "id": 1147233349,
    "node_id": "R_kgDORGFkRQ",
    "name": "Single-Page-CV-Project",
    "full_name": "HaithamAbuDraz/Single-Page-CV-Project",
    "private": false,
    "owner": {
      "login": "HaithamAbuDraz",
      "id": 131686041,
      "node_id": "U_kgDOB9lemQ",
      "avatar_url": "https://avatars.githubusercontent.com/u/131686041?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/HaithamAbuDraz",
      "html_url": "https://github.com/HaithamAbuDraz",
      "followers_url": "https://api.github.com/users/HaithamAbuDraz/followers",
      "following_url": "https://api.github.com/users/HaithamAbuDraz/following{/other_user}",
      "gists_url": "https://api.github.com/users/HaithamAbuDraz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/HaithamAbuDraz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/HaithamAbuDraz/subscriptions",
      "organizations_url": "https://api.github.com/users/HaithamAbuDraz/orgs",
      "repos_url": "https://api.github.com/users/HaithamAbuDraz/repos",
      "events_url": "https://api.github.com/users/HaithamAbuDraz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/HaithamAbuDraz/received_events",
      "type": "User",
      "user_view_type": "public",
      "site_admin": false
    },
    "html_url": "https://github.com/HaithamAbuDraz/Single-Page-CV-Project",
    "description": "A clean, responsive, and professional CV website for Haitham Abu Draz, showcasing skills, education, experience, and online profiles. Built with semantic HTML5 and modern CSS3.",
    "fork": false,
    "url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project",
    "forks_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/forks",
    "keys_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/teams",
    "hooks_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/hooks",
    "issue_events_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/issues/events{/number}",
    "events_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/events",
    "assignees_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/assignees{/user}",
    "branches_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/branches{/branch}",
    "tags_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/tags",
    "blobs_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/languages",
    "stargazers_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/stargazers",
    "contributors_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/contributors",
    "subscribers_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/subscribers",
    "subscription_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/subscription",
    "commits_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/contents/{+path}",
    "compare_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/merges",
    "archive_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/downloads",
    "issues_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/issues{/number}",
    "pulls_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/labels{/name}",
    "releases_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/releases{/id}",
    "deployments_url": "https://api.github.com/repos/HaithamAbuDraz/Single-Page-CV-Project/deployments",
    "created_at": "2026-02-01T12:28:51Z",
    "updated_at": "2026-03-28T10:01:03Z",
    "pushed_at": "2026-02-01T14:35:30Z",
    "git_url": "git://github.com/HaithamAbuDraz/Single-Page-CV-Project.git",
    "ssh_url": "git@github.com:HaithamAbuDraz/Single-Page-CV-Project.git",
    "clone_url": "https://github.com/HaithamAbuDraz/Single-Page-CV-Project.git",
    "svn_url": "https://github.com/HaithamAbuDraz/Single-Page-CV-Project",
    "homepage": null,
    "size": 19,
    "stargazers_count": 0,
    "watchers_count": 0,
    "language": "HTML",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": true,
    "has_pages": true,
    "has_discussions": false,
    "forks_count": 0,
    "mirror_url": null,
    "archived": false,
    "disabled": false,
    "open_issues_count": 0,
    "license": null,
    "allow_forking": true,
    "is_template": false,
    "web_commit_signoff_required": false,
    "has_pull_requests": true,
    "pull_request_creation_policy": "all",
    "topics": [

    ],
    "visibility": "public",
    "forks": 0,
    "open_issues": 0,
    "watchers": 0,
    "default_branch": "main"
  }
]
*/